In [1]:
import pandas as pd

In [4]:
df_corpus = pd.read_parquet('../data/processed/1_1_corpus.parquet')
df_corpus.head()

,dataHoraInicio,dataHoraFim,uriEvento,tipoDiscurso,urlTexto,urlAudio,urlVideo,keywords,sumario,deputado_id,idLegislatura,faseEvento.titulo,faseEvento.dataHoraInicio,faseEvento.dataHoraFim,is_outlier,text_level_1,text_level_2,text_level_3,text_level_4
0,2018-07-04T18:04,NaN,https://dadosabertos.camara.leg.br/api/v2/even...,PELA ORDEM,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"PL 10332/2018, PROJETO DE LEI ORDINÁRIA, PRIVA...",Conclamação dos Deputados à rejeição do projet...,178957,55,Ordem do Dia,NaN,NaN,False,"Sr. Presidente, eu quero dizer para todos os c...",presidente quero dizer para todos colegas que ...,presid quer diz tod coleg part vot priva dess ...,presid quer diz part vot priva dess distribu q...
1,2018-05-23T18:32,NaN,https://dadosabertos.camara.leg.br/api/v2/even...,ORIENTAÇÃO DE BANCADA,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"ORIENTAÇÃO DE BANCADA, PARECER, COMISSÃO MISTA...",Orientação de bancada para votação do parecer ...,178957,55,Ordem do Dia,NaN,NaN,False,"O Democratas, neste momento, quer pedir aos de...",democratas neste momento quer pedir aos demais...,democrat nest moment qu ped demal coleg dúv ne...,nest moment qu ped demal nenhum matér faz just...
2,2017-12-12T13:32,NaN,https://dadosabertos.camara.leg.br/api/v2/even...,PELA ORDEM,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"OTTOMAR DE SOUSA PINTO, EX-GOVERNADOR, RORAIMA...",Homenagem póstuma ao ex-Governador do Estado d...,178957,55,Ordem do Dia,NaN,NaN,False,"Sr. Presidente, Sras. e Srs. Deputados, hoje e...",presidente sras srs deputados hoje subo tribun...,presid sra sr deput hoj sub tribun faz pequen ...,presid faz just homen memór dess pesso import ...
3,2017-11-29T13:36,NaN,https://dadosabertos.camara.leg.br/api/v2/even...,BREVES COMUNICAÇÕES,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"BETÂNIA THOMÉ AVELINO, SECRETÁRIO-ADJUNTO, SEC...",Visita da Secretária Adjunta de Estado da Saúd...,178957,55,Breves Comunicações,NaN,NaN,False,"Sr. Presidente Carlos Manato, obrigado por est...",presidente carlos manato obrigado por esta opo...,presid carl manat obrig oportun pod deix regis...,presid obrig deix registr form algum visit est...
4,2017-11-28T18:50,NaN,https://dadosabertos.camara.leg.br/api/v2/even...,ORIENTAÇÃO DE BANCADA,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"ORIENTAÇÃO DE BANCADA, REQUERIMENTO DE DESTAQU...",Orientação de bancada para votação de requerim...,178957,55,Ordem do Dia,NaN,NaN,False,"Sr. Presidente, Sras. e Srs. Deputados, apesar...",presidente sras srs deputados apesar essa emen...,presid sra sr deput apes emend democrat deput ...,presid apes emend concord form algum porqu atr...

In [5]:
df_panel = pd.read_parquet('../data/processed/1_2_panel.parquet')
df_panel.head()

,dataHoraInicio,tipoDiscurso,keywords,sumario,deputado_id,idLegislatura,is_outlier,text_level_1,text_level_2,text_level_3,text_level_4,changes_tuple,idPartido,siglaPartido,party_change_count,EST,SE,CAT
0,2015-02-05 14:12:00+00:00,PEQUENO EXPEDIENTE,"DAVIDSON MAGALHÃES, DEPUTADO FEDERAL, ELEITOR,...",Agradecimento ao povo baiano pela eleição do o...,101309,55,False,"Sr. Presidente, Sras. e Srs. Deputados, pronun...",presidente sras srs deputados pronuncio pela p...,presid sra sr deput pronunci prim vez cond dep...,presid prim vez cond deput feder eleit est bah...,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,PCdoB,0,-0.744,0.04,0
1,2015-02-05 14:27:00+00:00,PELA ORDEM,"ITABUNA, BAHIA, HOMICIDIO, JOVEM, PREOCUPAÇÃO,...","Liderança do Município de Itabuna, Estado da B...",101309,55,False,"Sr. Presidente, Sras. e Srs. Deputados, depois...",presidente sras srs deputados depois ter feito...,presid sra sr deput ter feit apresent nest cas...,presid ter feit apresent nest cas gost cham du...,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,PCdoB,0,-0.744,0.04,0
2,2015-02-09 19:16:00+00:00,BREVES COMUNICAÇÕES,"BRASKEM S/A, INDÚSTRIA PETROQUÍMICA, CONTRATO,...",Importância do contrato firmado pela PETROBRAS...,101309,55,False,"Sr. Presidente, Sras. e Srs. Deputados, a Bras...",presidente sras srs deputados braskem maior pe...,presid sra sr deput brask mai petroquím brasil...,presid indústr dia exp praz contrat fornec naf...,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,PCdoB,0,-0.744,0.04,0
3,2015-02-10 16:24:00+00:00,PELA ORDEM,"DIA NACIONAL, DEFESA, MANUTENÇÃO, CAIXA ECONÔM...",Anúncio de mobilização em defesa da manutenção...,101309,55,False,"Sr. Presidente, Sras. e Srs. Deputados, o dia...",presidente sras srs deputados dia fevereiro se...,presid sra sr deput dia fever dia nacion lut d...,presid sra sr deput dia fever dia nacion lut d...,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,PCdoB,0,-0.744,0.04,0
4,2015-02-11 14:54:00+00:00,COMO LÍDER,"PETRÓLEO BRASILEIRO (PETROBRAS), DENOMINAÇÃO, ...",Contestação a declarações do Senador José Serr...,101309,55,False,"Sr. Presidente, Sras. e Srs. Deputados, agora,...",presidente sras srs deputados agora fevereiro ...,presid sra sr deput agor fever faz ano tent tr...,presid sra sr deput agor fever faz ano tent tr...,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,PCdoB,0,-0.744,0.04,0

In [9]:
df_panel.columns

Index(['dataHoraInicio', 'tipoDiscurso', 'keywords', 'sumario', 'deputado_id',
       'idLegislatura', 'is_outlier', 'text_level_1', 'text_level_2',
       'text_level_3', 'text_level_4', 'changes_tuple', 'idPartido',
       'siglaPartido', 'party_change_count', 'EST', 'SE', 'CAT'],
      dtype='object')

In [6]:
df_embeddings_sbert = pd.read_parquet('../data/processed/2_1_embeddings_sbert.parquet')
df_embeddings_sbert.head()

,deputado_id,dataHoraInicio,idLegislatura,party_change_count,changes_tuple,idPartido,text_level_2,CAT,EST,embedding
0,101309,2015-02-05 14:12:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados pronuncio pela p...,0,-0.744,"[0.00050607004, 0.088873886, -0.22730015, -0.0..."
1,101309,2015-02-05 14:27:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados depois ter feito...,0,-0.744,"[0.06601168, -0.12999704, -0.1973617, -0.14137..."
2,101309,2015-02-09 19:16:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados braskem maior pe...,0,-0.744,"[0.04212128, -0.16461372, -0.022062086, -0.010..."
3,101309,2015-02-10 16:24:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados dia fevereiro se...,0,-0.744,"[0.18772252, 0.063434936, -0.32960594, -0.1254..."
4,101309,2015-02-11 14:54:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados agora fevereiro ...,0,-0.744,"[0.073627844, -0.060019515, -0.037887152, -0.0..."

In [7]:
df_embeddings_word2vec = pd.read_parquet('../data/processed/2_1_embeddings_word2vec.parquet')
df_embeddings_word2vec.head()

,deputado_id,dataHoraInicio,idLegislatura,party_change_count,changes_tuple,idPartido,text_level_2,CAT,EST,embedding
0,101309,2015-02-05 14:12:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados pronuncio pela p...,0,-0.744,"[-0.48551947, -0.2891661, -0.216009, -0.243447..."
1,101309,2015-02-05 14:27:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados depois ter feito...,0,-0.744,"[-0.2568394, -0.55655265, 0.020959696, -0.0593..."
2,101309,2015-02-09 19:16:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados braskem maior pe...,0,-0.744,"[-0.15656854, -0.66647166, -0.26130503, 0.2760..."
3,101309,2015-02-10 16:24:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados dia fevereiro se...,0,-0.744,"[-0.07471043, -0.39289734, -0.07323206, 0.0738..."
4,101309,2015-02-11 14:54:00+00:00,55,0,"((Timestamp('2015-02-01 00:00:00+0000', tz='UT...",36779,presidente sras srs deputados agora fevereiro ...,0,-0.744,"[-0.16843851, -0.6420333, -0.09666848, 0.11436..."

In [10]:
df_lda = pd.read_parquet('../data/processed/2_2_panel_with_lda_topics.parquet')
df_lda.head()
df_lda.columns

Index(['dataHoraInicio', 'tipoDiscurso', 'keywords', 'sumario', 'deputado_id',
       'idLegislatura', 'is_outlier', 'text_level_1', 'text_level_2',
       'text_level_3', 'text_level_4', 'changes_tuple', 'idPartido',
       'siglaPartido', 'party_change_count', 'EST', 'SE', 'CAT', 'topic_id',
       'topic_vector'],
      dtype='object')

In [2]:
import pandas as pd
df_votos = pd.read_parquet('../data/raw/scrape_votes.parquet')
df_votos.columns

Index(['idVotacao', 'dataVotacao', 'deputado_id', 'siglaPartido', 'voto',
       'gov_orient', 'maioria_orient', 'minoria_orient', 'oposicao_orient',
       'blocos_orient'],
      dtype='object')

In [3]:
df_votos.head()

,idVotacao,dataVotacao,deputado_id,siglaPartido,voto,gov_orient,maioria_orient,minoria_orient,oposicao_orient,blocos_orient
0,43733-12,2003-02-25,74265,PPS,Abstenção,Sim,N/A,N/A,N/A,"{'AVANTE': None, 'Bl MdbPsdRepPode': None, 'Bl..."
1,43733-12,2003-02-25,74150,PTB,Sim,Sim,N/A,N/A,N/A,"{'AVANTE': None, 'Bl MdbPsdRepPode': None, 'Bl..."
2,43733-12,2003-02-25,74159,PT,Sim,Sim,N/A,N/A,N/A,"{'AVANTE': None, 'Bl MdbPsdRepPode': None, 'Bl..."
3,43733-12,2003-02-25,73555,PMDB,Sim,Sim,N/A,N/A,N/A,"{'AVANTE': None, 'Bl MdbPsdRepPode': None, 'Bl..."
4,43733-12,2003-02-25,74352,PSDB,Sim,Sim,N/A,N/A,N/A,"{'AVANTE': None, 'Bl MdbPsdRepPode': None, 'Bl..."

In [5]:
df_proposicoes = pd.read_csv('../data/raw/proposicoes/proposicoesAutores-2002.csv', sep=';')
df_proposicoes.head()
df_proposicoes.columns

Index(['idProposicao', 'uriProposicao', 'idDeputadoAutor', 'uriAutor',
       'codTipoAutor', 'tipoAutor', 'nomeAutor', 'siglaPartidoAutor',
       'uriPartidoAutor', 'siglaUFAutor', 'ordemAssinatura', 'proponente'],
      dtype='object')

In [11]:
df_covariates = pd.read_parquet('../data/processed/3_1_final_covariates_panel.parquet')
df_covariates.head()

,dataHoraInicio,tipoDiscurso,keywords,sumario,deputado_id,idLegislatura,is_outlier,text_level_1,text_level_2,text_level_3,...,SE,CAT,topic_id,topic_vector,data_inicio_carreira,data_ultimo_partido,gov_loyalty_12m,prop_activity_annual,career_tenure_years,party_tenure_months
0,2007-11-21 15:16:00,PEQUENO EXPEDIENTE,"SECA, MUNICÍPIOS, MG, DIVISA, BA, SITUAÇÃO, CA...",Apelo aos governantes para atendimento às reiv...,3151,53,False,"Sr. Presidente, é uma honra ver V.Exa., conter...",presidente uma honra ver exa conterrâneo amigo...,presid honr ver exa conterrâne amig presid ses...,...,0.046,2,5,"[9.174312137682903e-05, 9.174312108710947e-05,...",2007-02-01,2007-04-23,0.5,31.0,0.80,7.0
1,2009-12-02 15:26:00,BREVES COMUNICAÇÕES,"UNIVERSIDADE FEDERAL DE MINAS GERAIS, UFMG, MU...",Expansão do campus da Universidade Federal de ...,3151,53,False,"Sr. Presidente, Sras. e Srs. Deputados, é com ...",presidente sras srs deputados com satisfação q...,presid sra sr deput satisf hoj ocup tribun des...,...,0.041,2,14,"[0.00010080645299443065, 0.0001008064530491119...",2007-02-01,2007-04-23,0.5,20.0,2.83,31.3
2,2010-07-14 17:20:00,PELA ORDEM,"MUNICÍPIO, MONTES CLAROS, MG, ANIVERSÁRIO, EMA...",Transcurso do 153º aniversário de emancipação ...,3151,53,True,"Sr. Presidente, Sras. e Srs. Deputados, é com ...",presidente sras srs deputados com muito prazer...,presid sra sr deput praz ocup hoj tribun comem...,...,0.041,2,14,"[0.08975194533912215, 6.896551816621165e-05, 6...",2007-02-01,2007-04-23,0.5,16.0,3.45,38.7
3,2011-06-16 15:51:00,GRANDE EXPEDIENTE,"ADMINISTRAÇÃO ESTADUAL, AÉCIO NEVES, EX GOVERN...",Realização de investimentos na região norte do...,3151,54,True,"Sr. Presidente, Sras. e Srs. Deputados, telesp...",presidente sras srs deputados telespectadores ...,presid sra sr deput telespect câm senh senh as...,...,0.041,2,5,"[6.443299142147803e-05, 6.443299094087758e-05,...",2007-02-01,2007-04-23,0.5,25.0,4.37,49.8
4,2007-04-26 16:54:00,GRANDE EXPEDIENTE,"MARCHA PARA JESUS, VETO, AUTORIDADE MUNICIPAL,...",Inconformismo com a decisão de autoridades do ...,3155,53,True,"Ilustre Sr. Presidente, nobres Sras. e Srs. De...",ilustre presidente nobres sras srs deputados t...,ilustr presid nobr sra sr deput telespect prec...,...,0.046,2,16,"[0.16167835923585616, 0.05522211853924947, 0.0...",2007-02-01,2007-04-23,0.5,29.0,0.23,0.1

In [13]:
df_covariates.head(50).to_csv('covariates_sample.csv', index=False)

In [12]:
df_covariates.columns

Index(['dataHoraInicio', 'tipoDiscurso', 'keywords', 'sumario', 'deputado_id',
       'idLegislatura', 'is_outlier', 'text_level_1', 'text_level_2',
       'text_level_3', 'text_level_4', 'changes_tuple', 'idPartido',
       'siglaPartido', 'party_change_count', 'EST', 'SE', 'CAT', 'topic_id',
       'topic_vector', 'data_inicio_carreira', 'data_ultimo_partido',
       'gov_loyalty_12m', 'prop_activity_annual', 'career_tenure_years',
       'party_tenure_months'],
      dtype='object')

In [3]:
df_scrape = pd.read_parquet('../data/processed/data_lda_topics.parquet')
df_scrape

,deputado_id,dataHoraInicio,topic_id,topic_vector
0,178957,2018-07-04T18:04,19,"[0.0029411764755972107, 0.0029411766195449308,..."
1,178957,2018-05-23T18:32,4,"[0.005555555661377111, 0.005555555654825844, 0..."
2,178957,2017-12-12T13:32,5,"[0.0006756756785090936, 0.07542073234921752, 0..."
3,178957,2017-11-29T13:36,8,"[0.15292235005465343, 0.005000000011593403, 0...."
4,178957,2017-11-28T18:50,4,"[0.206092652298833, 0.1449395182454314, 0.0055..."
...,...,...,...,...
372396,73645,2003-03-19T22:18,2,"[0.14396129679024958, 0.0016129032523890723, 0..."
372397,73645,2003-03-19T19:50,2,"[0.000806451635459022, 0.0008064516207919303, ..."
372398,73645,2003-03-19T16:48,2,"[0.1325000520347709, 0.001190476206461993, 0.4..."
372399,73645,2003-02-26T18:14,8,"[0.03754073594197344, 0.001041666681590149, 0...."
372400,73645,2003-02-18T17:50,13,"[0.000505050514298843, 0.0005050505088962946, ..."

In [2]:
import pandas as pd
df_panel_refactor = pd.read_parquet('../data/processed/data_panel.parquet')

In [4]:
df_panel_refactor.columns

Index(['dataHoraInicio', 'tipoDiscurso', 'keywords', 'sumario', 'deputado_id',
       'idLegislatura', 'is_outlier', 'text_level_1', 'text_level_2',
       'text_level_3', 'text_level_4', 'idPartido', 'siglaPartido',
       'party_change_count', 'EST', 'SE', 'CAT', 'gov_loyalty_12m',
       'career_tenure_years', 'party_tenure_months', 'embedding', 'topic_id',
       'topic_vector', 'prop_activity_annual'],
      dtype='object')